name: News Page UI Tests

# Triggers
on:
  push:
  pull_request:
  workflow_dispatch:  # run manually from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      - name: Run tests (headless)
        run: mvn -B -DHEADLESS=true clean test

      # Upload Cucumber HTML report
      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-test-report
          path: target/cucumber-report.html
          retention-days: 30
          if-no-files-found: warn

      # Upload Screenshots (if any tests failed)
      - name: Upload Test Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: Screenshots/
          retention-days: 30
          if-no-files-found: ignore

      # Upload Surefire test reports (XML and TXT)
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
          retention-days: 30
          if-no-files-found: warn

      # Upload failed scenarios rerun file
      - name: Upload Failed Scenarios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-scenarios
          path: target/failed_scenarios.txt
          retention-days: 30
          if-no-files-found: ignore
