name: News Page UI Tests

# Triggers
on:
  push:
  pull_request:
  workflow_dispatch:  # run manually from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      - name: Run tests (headless)
        run: mvn -B -DHEADLESS=true clean test

      # (Optional) list report files in logs for quick sanity check
      - name: List report files
        if: always()
        run: |
          echo "Listing target directory:"
          ls -la target || true
          echo "If cucumber-report.html exists, it will be uploaded in the next step."

      # Upload the HTML report even if tests fail
      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/cucumber-report.html
            target/**/*.png
          if-no-files-found: warn
          retention-days: 7
